export const FETCH_DATA_STARTED = "FETCH_DATA_STARTED";
export const RECEIVE_DATA_SUCCESS = "RECEIVE_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const UPDATE_DATA_ROW = "UPDATE_DATA_ROW";
export const POST_ADD_DATA_ROW_STARTED = "POST_ADD_DATA_ROW_STARTED";
export const POST_ADD_DATA_ROW_SUCCESS = "POST_ADD_DATA_ROW_SUCCESS";
export const POST_ADD_DATA_ROW_FAILED = "POST_ADD_DATA_ROW_FAILED";
